%Adjetivos con A
adjetivo(["aburrido"],["bored"],m,s):-!.
adjetivo(["aburridos"],["bored"],m,p):-!.
adjetivo(["aburrida"],["bored"],f,s):-!.
adjetivo(["aburridas"],["bored"],f,p):-!.
adjetivo(["acido"],["acid"],m,s):-!.
adjetivo(["acidos"],["acid"],m,p):-!.
adjetivo(["alto"],["tall"],m,s):-!.
adjetivo(["altos"],["tall"],m,s):-!.
adjetivo(["alta"],["tall"],f,s):-!.
adjetivo(["altas"],["tall"],f,s):-!.
adjetivo(["amargo"],["bitter"],m,s):-!.
adjetivo(["amargos"],["bitter"],m,p):-!.
adjetivo(["amarga"],["bitter"],f,s):-!.
adjetivo(["amargas"],["bitter"],f,p):-!.
adjetivo(["apuesto"],["handsome"],m,s):-!.
adjetivo(["apuestos"],["handsome"],m,p):-!.
adjetivo(["ancho"],["wide"],m,s):-!.
adjetivo(["anchos"],["wide"],m,p):-!.
adjetivo(["ancha"],["wide"],f,s):-!.
adjetivo(["anchas"],["wide"],f,p):-!.
adjetivo(["azul"],["blue"],m,s):-!.
adjetivo(["azules"],["blue"],m,p):-!.
adjetivo(["azul"],["blue"],f,s):-!.
adjetivo(["azules"],["blue"],f,p):-!.
adjetivo(["alegre"],["cheerful"],m,s):-!.
adjetivo(["alegres"],["cheerful"],m,p):-!.
adjetivo(["alegre"],["cheerful"],f,s):-!.
adjetivo(["alegres"],["cheerful"],f,p):-!.
adjetivo(["atrevido"],["daring"],m,s):-!.
adjetivo(["atrevidos"],["daring"],m,p):-!.
adjetivo(["atrevida"],["daring"],f,s):-!.
adjetivo(["atrevidas"],["daring"],f,p):-!.
adjetivo(["amarillo"],["yellow"],m,s):-!.
adjetivo(["amarillos"],["yellow"],m,p):-!.
adjetivo(["amarilla"],["yellow"],f,s):-!.
adjetivo(["amarillas"],["yellow"],f,p):-!.

%Adjetivos con B
adjetivo(["bajo"],["low"],m,s):-!.
adjetivo(["bajos"],["low"],m,p):-!.
adjetivo(["baja"],["low"],f,s):-!.
adjetivo(["bajas"],["low"],f,p):-!.
adjetivo(["blanco"],["white"],m,s):-!.
adjetivo(["blancos"],["white"],m,p):-!.
adjetivo(["blanca"],["white"],f,s):-!.
adjetivo(["blancas"],["white"],f,p):-!.
adjetivo(["blando"],["soft"],m,s):-!.
adjetivo(["blandos"],["soft"],m,p):-!.
adjetivo(["blanda"],["soft"],f,s):-!.
adjetivo(["blandas"],["soft"],f,p):-!.
adjetivo(["bonito"],["beautiful"],m,s):-!.
adjetivo(["bonitos"],["pretty"],m,p):-!.
adjetivo(["bonita"],["pretty"],f,s):-!.
adjetivo(["bonitas"],["pretty"],f,p):-!.
adjetivo(["bueno"],["good"],m,s):-!.
adjetivo(["buenos"],["good"],m,p):-!.
adjetivo(["buena"],["good"],f,s):-!.
adjetivo(["buenas"],["good"],f,p):-!.
adjetivo(["barato"],["cheap"],m,s):-!.
adjetivo(["baratos"],["cheap"],m,p):-!.
adjetivo(["barata"],["cheap"],f,s):-!.
adjetivo(["baratas"],["cheap"],f,p):-!.

%Adjetivos con C
adjetivo(["caliente"],["hot"],m,s):-!.
adjetivo(["calientes"],["hot"],m,p):-!.
adjetivo(["caliente"],["hot"],f,s):-!.
adjetivo(["calientes"],["hot"],f,p):-!.
adjetivo(["calido"],["warm"],m,s):-!.
adjetivo(["calidos"],["warm"],m,p):-!.
adjetivo(["calida"],["warm"],f,s):-!.
adjetivo(["calidas"],["warm"],f,p):-!.
adjetivo(["capaz"],["capable"],m,s):-!.
adjetivo(["capaces"],["capable"],m,p):-!.
adjetivo(["capaz"],["capable"],f,s):-!.
adjetivo(["capaces"],["capable"],f,p):-!.
adjetivo(["comun"],["common"],m,s):-!.
adjetivo(["comunes"],["common"],m,p):-!.
adjetivo(["comun"],["common"],f,s):-!.
adjetivo(["comunes"],["common"],f,p):-!.
adjetivo(["conocido"],["known"],m,s):-!.
adjetivo(["conocidos"],["known"],m,p):-!.
adjetivo(["conocida"],["known"],f,s):-!.
adjetivo(["conocidas"],["known"],f,p):-!.
adjetivo(["contento"],["happy"],m,s):-!.
adjetivo(["contentos"],["happy"],m,p):-!.
adjetivo(["contenta"],["happy"],f,s):-!.
adjetivo(["contentas"],["happy"],f,p):-!.
adjetivo(["corto"],["short"],m,s):-!.
adjetivo(["cortos"],["short"],m,p):-!.
adjetivo(["corta"],["short"],f,s):-!.
adjetivo(["cortas"],["short"],f,p):-!.
adjetivo(["cerca"],["near"],m,s):-!.
adjetivo(["cerca"],["near"],f,s):-!.
adjetivo(["cerca"],["near"],m,p):-!.
adjetivo(["cerca"],["near"],f,p):-!.
adjetivo(["caro"],["expensive"],m,s):-!.
adjetivo(["caros"],["expensive"],m,p):-!.
adjetivo(["cara"],["expensive"],f,s):-!.
adjetivo(["caras"],["expensive"],f,p):-!.
adjetivo(["cansado"],["tired"],m,s):-!.
adjetivo(["cansados"],["tired"],m,p):-!.
adjetivo(["cansada"],["tired"],f,s):-!.
adjetivo(["cansadas"],["tired"],f,p):-!.
adjetivo(["cafe"],["brown"],m,s):-!.
adjetivo(["cafes"],["brown"],m,p):-!.
adjetivo(["cafe"],["brown"],f,s):-!.
adjetivo(["cafes"],["brown"],f,p):-!.

%Adjetivos con D
adjetivo(["debil"],["weak"],m,s):-!.
adjetivo(["debiles"],["weak"],m,p):-!.
adjetivo(["debil"],["weak"],f,s):-!.
adjetivo(["debiles"],["weak"],f,p):-!.
adjetivo(["delgado"],["thin"],m,s):-!.
adjetivo(["delgados"],["thin"],m,p):-!.
adjetivo(["delgada"],["thin"],f,s):-!.
adjetivo(["delgadas"],["thin"],f,p):-!.
adjetivo(["derecho"],["right"],m,s):-!.
adjetivo(["derecha"],["right"],f,s):-!.
adjetivo(["diferente"],["different"],m,s):-!.
adjetivo(["diferentes"],["different"],m,p):-!.
adjetivo(["diferente"],["different"],f,s):-!.
adjetivo(["diferentes"],["different"],f,p):-!.
adjetivo(["dificil"],["difficult"],m,s):-!.
adjetivo(["dificiles"],["difficult"],m,s):-!.
adjetivo(["dificil"],["difficult"],f,s):-!.
adjetivo(["dificiles"],["difficult"],f,s):-!.
adjetivo(["divertido"],["funny"],m,s):-!.
adjetivo(["divertidos"],["funny"],m,p):-!.
adjetivo(["divertida"],["funny"],f,s):-!.
adjetivo(["divertidas"],["funny"],f,p):-!.
adjetivo(["dulce"],["sweet"],m,s):-!.
adjetivo(["dulces"],["sweet"],m,p):-!.
adjetivo(["dulce"],["sweet"],f,s):-!.
adjetivo(["dulces"],["sweet"],f,p):-!.
adjetivo(["duro"],["hard"],m,s):-!.
adjetivo(["duros"],["hard"],m,p):-!.
adjetivo(["dura"],["hard"],f,s):-!.
adjetivo(["duras"],["hard"],f,p):-!.
adjetivo(["despejado"],["clear"],m,s):-!.
adjetivo(["despejados"],["clear"],m,p):-!.
adjetivo(["despejada"],["clear"],f,s):-!.
adjetivo(["despejadas"],["clear"],f,p):-!.

%Adjetivos con E
adjetivo(["enfermo"],["sick"],m,s):-!.
adjetivo(["enfermos"],["sick"],m,p):-!.
adjetivo(["enferma"],["sick"],f,s):-!.
adjetivo(["enfermas"],["sick"],f,p):-!.
adjetivo(["estrecho"],["tight"],m,s):-!.
adjetivo(["estrechos"],["tight"],m,p):-!.
adjetivo(["estrecha"],["tight"],f,s):-!.
adjetivo(["estrechas"],["tight"],f,p):-!.
adjetivo(["exterior"],["outside"],m,s):-!.
adjetivo(["exteriores"],["outside"],m,p):-!.
adjetivo(["exterior"],["outside"],f,s):-!.
adjetivo(["exteriores"],["outside"],f,p):-!.

%Adjetivos con F
adjetivo(["facil"],["easy"],m,s):-!.
adjetivo(["faciles"],["easy"],m,p):-!.
adjetivo(["facil"],["easy"],f,s):-!.
adjetivo(["faciles"],["easy"],f,p):-!.
adjetivo(["falso"],["false"],m,s):-!.
adjetivo(["falsos"],["false"],m,p):-!.
adjetivo(["falsa"],["false"],f,s):-!.
adjetivo(["falsas"],["false"],f,p):-!.
adjetivo(["famoso"],["famous"],m,s):-!.
adjetivo(["famosos"],["famous"],m,p):-!.
adjetivo(["famosa"],["famous"],f,s):-!.
adjetivo(["famosas"],["famous"],f,p):-!.
adjetivo(["feo"],["ugly"],m,s):-!.
adjetivo(["feos"],["ugly"],m,p):-!.
adjetivo(["fea"],["ugly"],f,s):-!.
adjetivo(["feas"],["ugly"],f,p):-!.
adjetivo(["final"],["final"],m,s):-!.
adjetivo(["finales"],["final"],m,p):-!.
adjetivo(["final"],["final"],f,s):-!.
adjetivo(["finales"],["final"],f,p):-!.
adjetivo(["fresco"],["fresh"],m,s):-!.
adjetivo(["frescos"],["fresh"],m,p):-!.
adjetivo(["fresca"],["fresh"],f,s):-!.
adjetivo(["frescas"],["fresh"],f,p):-!.
adjetivo(["frio"],["cold"],m,s):-!.
adjetivo(["frios"],["cold"],m,p):-!.
adjetivo(["fria"],["cold"],f,s):-!.
adjetivo(["frias"],["cold"],f,p):-!.
adjetivo(["fuerte"],["strong"],m,s):-!.
adjetivo(["fuertes"],["strong"],m,p):-!.
adjetivo(["fuerte"],["strong"],f,s):-!.
adjetivo(["fuertes"],["strong"],f,p):-!.
adjetivo(["flaco"],["skinny"],m,s):-!.
adjetivo(["flacos"],["skinny"],m,p):-!.
adjetivo(["flaca"],["skinny"],f,s):-!.
adjetivo(["flacas"],["skinny"],f,p):-!.
adjetivo(["fiel"],["loyal"],m,s):-!.
adjetivo(["fieles"],["loyal"],m,p):-!.
adjetivo(["fiel"],["loyal"],f,s):-!.
adjetivo(["fieles"],["loyal"],f,p):-!.
adjetivo(["feliz"],["happy"],m,s):-!.
adjetivo(["felices"],["happy"],m,p):-!.
adjetivo(["feliz"],["happy"],f,s):-!.
adjetivo(["felices"],["happy"],f,p):-!.

%Adjetivos con G
adjetivo(["gordo"],["fat"],m,s):-!.
adjetivo(["gordos"],["fat"],m,p):-!.
adjetivo(["gorda"],["fat"],f,s):-!.
adjetivo(["gordas"],["fat"],f,p):-!.
adjetivo(["grande"],["big"],m,s):-!.
adjetivo(["grandes"],["big"],m,p):-!.
adjetivo(["grande"],["big"],f,s):-!.
adjetivo(["grandes"],["big"],f,p):-!.
adjetivo(["guapo"],["handsome"],s,m):-!.
adjetivo(["guapos"],["handsome"],s,p):-!.
adjetivo(["guapa"],["beautiful"],f,m):-!.
adjetivo(["guapas"],["beautiful"],f,p):-!.
adjetivo(["grueso"],["thick"],m,s):-!.
adjetivo(["gruesos"],["thick"],m,p):-!.
adjetivo(["gruesa"],["thick"],f,s):-!.
adjetivo(["gruesas"],["thick"],f,p):-!.

adjetivo(["gratis"],["free"],m,s):-!.
adjetivo(["gratis"],["free"],m,p):-!.
adjetivo(["gratis"],["free"],f,s):-!.
adjetivo(["gratis"],["free"],f,p):-!.
adjetivo(["gigante"],["giant"],m,s):-!.
adjetivo(["gigantes"],["giant"],m,p):-!.
adjetivo(["gigante"],["giant"],f,s):-!.
adjetivo(["gigantes"],["giant"],f,p):-!.


%Adjetivos con H
adjetivo(["humedo"],["damp"],m,s):-!.
adjetivo(["humedos"],["damp"],m,p):-!.
adjetivo(["humeda"],["damp"],f,s):-!.
adjetivo(["humedas"],["damp"],f,p):-!.
adjetivo(["hermoso"],["handsome"],m,s):-!.
adjetivo(["hermosos"],["handsome"],m,p):-!.
adjetivo(["hermosa"],["beautiful"],f,s):-!.
adjetivo(["hermosas"],["beautiful"],f,p):-!.


%Adjetivos con I
adjetivo(["igual"],["same"],m,s):-!.
adjetivo(["iguales"],["same"],m,p):-!.
adjetivo(["igual"],["same"],f,s):-!.
adjetivo(["iguales"],["same"],f,p):-!.
adjetivo(["imposible"],["impossible"],m,s):-!.
adjetivo(["imposibles"],["impossible"],m,p):-!.
adjetivo(["imposible"],["impossible"],f,s):-!.
adjetivo(["imposibles"],["impossible"],f,p):-!.
adjetivo(["interesante"],["interesting"],m,s):-!.
adjetivo(["interesantes"],["interesting"],m,p):-!.
adjetivo(["interesante"],["interesting"],f,s):-!.
adjetivo(["interesantes"],["interesting"],f,p):-!.
adjetivo(["inutil"],["useless"],m,s):-!.
adjetivo(["inutiles"],["useless"],m,p):-!.
adjetivo(["inutil"],["useless"],f,s):-!.
adjetivo(["inutiles"],["useless"],f,p):-!.
adjetivo(["izquierdo"],["left"],m,s):-!.
adjetivo(["izquierdos"],["left"],m,p):-!.
adjetivo(["izquierda"],["left"],f,s):-!.
adjetivo(["izquierdas"],["left"],f,p):-!.
adjetivo(["inteligente"],["smart"],m,s):-!.
adjetivo(["inteligentes"],["smart"],m,p):-!.
adjetivo(["inteligente"],["smart"],f,s):-!.
adjetivo(["inteligentes"],["smart"],f,p):-!.

%Adjetivos con J
adjetivo(["joven"],["young"],m,s):-!.
adjetivo(["jovenes"],["young"],m,p):-!.
adjetivo(["joven"],["young"],f,s):-!.
adjetivo(["jovenes"],["young"],f,p):-!.


%Adjetivos con L
adjetivo(["largo"],["long"],m,s):-!.
adjetivo(["largos"],["long"],m,p):-!.
adjetivo(["larga"],["long"],f,s):-!.
adjetivo(["largas"],["long"],f,p):-!.
adjetivo(["lento"],["slow"],m,s):-!.
adjetivo(["lentos"],["slow"],m,p):-!.
adjetivo(["lenta"],["slow"],f,s):-!.
adjetivo(["lentas"],["slow"],f,p):-!.
adjetivo(["lejos"],["far"],m,s):-!.
adjetivo(["lejos"],["far"],m,p):-!.
adjetivo(["lejos"],["far"],f,s):-!.
adjetivo(["lejos"],["far"],f,p):-!.
adjetivo(["liviano"],["light"],m,s):-!.
adjetivo(["livianos"],["light"],m,p):-!.
adjetivo(["liviana"],["light"],f,s):-!.
adjetivo(["livianas"],["light"],f,p):-!.
adjetivo(["limpio"],["clean"],m,s):-!.
adjetivo(["limpios"],["clean"],m,p):-!.
adjetivo(["limpia"],["clean"],f,s):-!.
adjetivo(["limpias"],["clean"],f,p):-!.
adjetivo(["lleno"],["full"],m,s):-!.
adjetivo(["llenos"],["full"],m,p):-!.
adjetivo(["llena"],["full"],f,s):-!.
adjetivo(["llenas"],["full"],f,p):-!.


%Adjetivos con M
adjetivo(["malo"],["bad"],m,s):-!.
adjetivo(["malos"],["bad"],m,p):-!.
adjetivo(["mala"],["bad"],f,s):-!.
adjetivo(["malas"],["bad"],f,p):-!.
adjetivo(["mejor"],["best"],m,s):-!.
adjetivo(["mejores"],["best"],m,p):-!.
adjetivo(["mejor"],["best"],f,s):-!.
adjetivo(["mejores"],["best"],f,p):-!.
adjetivo(["muerto"],["dead"],m,s):-!.
adjetivo(["muertos"],["dead"],m,p):-!.
adjetivo(["muerta"],["dead"],f,s):-!.
adjetivo(["muertas"],["dead"],f,p):-!.
adjetivo(["mojado"],["wet"],m,s):-!.
adjetivo(["mojados"],["wet"],m,p):-!.
adjetivo(["mojada"],["wet"],f,s):-!.
adjetivo(["mojadas"],["wet"],f,p):-!.

%Adjetivos con N;!:-!.
adjetivo(["nacional"],["national"],m,s):-!.
adjetivo(["nacionales"],["national"],m,p):-!.
adjetivo(["nacional"],["national"],f,s):-!.
adjetivo(["nacionales"],["national"],f,p):-!.
adjetivo(["natural"],["natural"],m,s):-!.
adjetivo(["naturales"],["natural"],m,p):-!.
adjetivo(["natural"],["natural"],f,s):-!.
adjetivo(["naturales"],["natural"],f,p):-!.
adjetivo(["negro"],["black"],m,s):-!.
adjetivo(["negros"],["black"],m,p):-!.
adjetivo(["negra"],["black"],f,s):-!.
adjetivo(["negras"],["black"],f,p):-!.
adjetivo(["nuevo"],["new"],m,s):-!.
adjetivo(["nuevos"],["new"],m,p):-!.
adjetivo(["nueva"],["new"],f,s):-!.
adjetivo(["nuevas"],["new"],f,p):-!.
adjetivo(["nublado"],["cloudy"],m,s):-!.
adjetivo(["nublados"],["cloudy"],m,p):-!.
adjetivo(["nublado"],["cloudy"],f,s):-!.
adjetivo(["nublados"],["cloudy"],f,p):-!.

%Adjetivos con O
adjetivo(["oscuro"],["dark"],m,s):-!.
adjetivo(["oscuros"],["dark"],m,p):-!.
adjetivo(["oscura"],["dark"],f,s):-!.
adjetivo(["oscuras"],["dark"],f,p):-!.

%Adjetivos con P
adjetivo(["peor"],["worse"],m,s):-!.
adjetivo(["peores"],["worse"],m,p):-!.
adjetivo(["peor"],["worse"],f,s):-!.
adjetivo(["peores"],["worse"],f,p):-!.
adjetivo(["pequeño"],["little"],m,s):-!.
adjetivo(["pequeños"],["little"],m,p):-!.
adjetivo(["pequeña"],["little"],f,s):-!.
adjetivo(["pequeñas"],["little"],f,p):-!.
adjetivo(["perfecto"],["perfect"],m,s):-!.
adjetivo(["perfectos"],["perfect"],m,p):-!.
adjetivo(["perfecta"],["perfect"],f,s):-!.
adjetivo(["perfectas"],["perfect"],f,p):-!.
adjetivo(["pobre"],["poor"],m,s):-!.
adjetivo(["pobres"],["poor"],m,p):-!.
adjetivo(["pobre"],["poor"],f,s):-!.
adjetivo(["pobres"],["poor"],f,p):-!.

adjetivo(["popular"],["popular"],m,s):-!.
adjetivo(["populares"],["popular"],m,p):-!.
adjetivo(["popular"],["popular"],f,s):-!.
adjetivo(["populares"],["popular"],f,p):-!.
adjetivo(["posible"],["possible"],m,s):-!.
adjetivo(["posibles"],["possible"],m,p):-!.
adjetivo(["posible"],["possible"],f,s):-!.
adjetivo(["posibles"],["possible"],f,p):-!.
adjetivo(["primero"],["first"],m,s):-!.
adjetivo(["primeros"],["first"],m,p):-!.
adjetivo(["primera"],["first"],f,s):-!.
adjetivo(["primeras"],["first"],f,p):-!.
adjetivo(["principal"],["principal"],m,s):-!.
adjetivo(["principales"],["principal"],m,p):-!.
adjetivo(["principal"],["principal"],f,s):-!.
adjetivo(["principales"],["principal"],f,p):-!.
adjetivo(["pesado"],["heavy"],m,s):-!.
adjetivo(["pesados"],["heavy"],m,p):-!.
adjetivo(["pesada"],["heavy"],f,s):-!.
adjetivo(["pesadas"],["heavy"],f,p):-!.
adjetivo(["profundo"],["deep"],m,s):-!.
adjetivo(["profundos"],["deep"],m,p):-!.
adjetivo(["profunda"],["deep"],f,s):-!.
adjetivo(["profundas"],["deep"],f,p):-!.
adjetivo(["peligroso"],["dangerous"],m,s):-!.
adjetivo(["peligrosos"],["dangerous"],m,p):-!.
adjetivo(["peligrosa"],["dangerous"],f,s):-!.
adjetivo(["peligrosas"],["dangerous"],f,p):-!.

%Adjetivos con R
adjetivo(["rapido"],["fast"],m,s):-!.
adjetivo(["rapidos"],["fast"],m,p):-!.
adjetivo(["rapida"],["fast"],f,s):-!.
adjetivo(["rapidas"],["fast"],f,p):-!.
adjetivo(["raro"],["rare"],m,s):-!.
adjetivo(["raros"],["rare"],m,p):-!.
adjetivo(["rara"],["rare"],f,s):-!.
adjetivo(["raras"],["rare"],f,p):-!.
adjetivo(["real"],["real"],m,s):-!.
adjetivo(["reales"],["real"],m,p):-!.
adjetivo(["real"],["real"],f,s):-!.
adjetivo(["reales"],["real"],f,p):-!.
adjetivo(["recto"],["straight"],m,s):-!.
adjetivo(["rectos"],["straight"],m,p):-!.
adjetivo(["recta"],["straight"],f,s):-!.
adjetivo(["rectas"],["straight"],f,p):-!.
adjetivo(["rico"],["rich"],m,s):-!.
adjetivo(["ricos"],["rich"],m,p):-!.
adjetivo(["rica"],["rich"],f,s):-!.
adjetivo(["ricas"],["rich"],f,p):-!.
adjetivo(["rojo"],["red"],m,s):-!.
adjetivo(["rojos"],["red"],m,p):-!.
adjetivo(["roja"],["red"],f,s):-!.
adjetivo(["rojas"],["red"],f,p):-!.

%Adjetivos con S
adjetivo(["salado"],["salty"],m,s):-!.
adjetivo(["salados"],["salty"],m,p):-!.
adjetivo(["salada"],["salty"],f,s):-!.
adjetivo(["saladas"],["salty"],f,p):-!.
adjetivo(["sano"],["healthy"],m,s):-!.
adjetivo(["sanos"],["healthy"],m,p):-!.
adjetivo(["sana"],["healthy"],f,s):-!.
adjetivo(["sanas"],["healthy"],f,p):-!.
adjetivo(["seco"],["dry"],m,s):-!.
adjetivo(["secos"],["dry"],m,p):-!.
adjetivo(["seca"],["dry"],f,s):-!.
adjetivo(["secas"],["dry"],f,p):-!.
adjetivo(["segundo"],["second"],m,s):-!.
adjetivo(["segundos"],["second"],m,p):-!.
adjetivo(["segunda"],["second"],f,s):-!.
adjetivo(["segundas"],["second"],f,p):-!.
adjetivo(["simple"],["simple"],m,s):-!.
adjetivo(["simples"],["simple"],m,p):-!.
adjetivo(["simple"],["simple"],f,s):-!.
adjetivo(["simples"],["simple"],f,p):-!.
adjetivo(["social"],["social"],m,s):-!.
adjetivo(["sociales"],["social"],m,p):-!.
adjetivo(["social"],["social"],f,s):-!.
adjetivo(["sociales"],["social"],f,p):-!.
adjetivo(["solo"],["alone"],m,s):-!.
adjetivo(["solos"],["alone"],m,p):-!.
adjetivo(["sola"],["alone"],f,s):-!.
adjetivo(["solas"],["alone"],f,p):-!.
adjetivo(["soleado"],["sunny"],m,s):-!.
adjetivo(["soleados"],["sunny"],m,p):-!.
adjetivo(["soleada"],["sunny"],f,s):-!.
adjetivo(["soleadas"],["sunny"],f,p):-!.
adjetivo(["sucio"],["dirty"],m,s):-!.
adjetivo(["sucios"],["dirty"],m,p):-!.
adjetivo(["sucia"],["dirty"],f,s):-!.
adjetivo(["sucias"],["dirty"],f,p):-!.

%Adjetivos con T
adjetivo(["timido"],["shy"],m,s):-!.
adjetivo(["timidos"],["shy"],m,p):-!.
adjetivo(["timida"],["shy"],f,s):-!.
adjetivo(["timidas"],["shy"],f,p):-!.
adjetivo(["tonto"],["silly"],m,s):-!.
adjetivo(["tontos"],["silly"],m,p):-!.
adjetivo(["tonta"],["silly"],f,s):-!.
adjetivo(["tontas"],["silly"],f,p):-!.
adjetivo(["triste"],["sad"],m,s):-!.
adjetivo(["tristes"],["sad"],m,p):-!.
adjetivo(["triste"],["sad"],f,s):-!.
adjetivo(["tristes"],["sad"],f,p):-!.
adjetivo(["temprano"],["early"],m,s):-!.
adjetivo(["temprano"],["early"],f,s):-!.
adjetivo(["tarde"],["late"],m,s):-!.
adjetivo(["tarde"],["late"],f,s):-!.

%Adjetivos con H
adjetivo(["hambriento"],["hungry"],m,s):-!.
adjetivo(["hambrientos"],["hungry"],m,p):-!.
adjetivo(["hambriento"],["hungry"],f,s):-!.
adjetivo(["hambrientos"],["hungry"],f,p):-!.

%Adjetivos con U
adjetivo(["util"],["useful"],m,s):-!.
adjetivo(["utiles"],["useful"],m,p):-!.
adjetivo(["util"],["useful"],f,s):-!.
adjetivo(["utiles"],["useful"],f,p):-!.

%Adjetivos con V
adjetivo(["verdadero"],["true"],m,s):-!.
adjetivo(["verdaderos"],["true"],m,p):-!.
adjetivo(["verdadera"],["true"],f,s):-!.
adjetivo(["verdaderas"],["true"],f,p):-!.
adjetivo(["verde"],["green"],m,s):-!.
adjetivo(["verdes"],["green"],m,p):-!.
adjetivo(["verde"],["green"],f,s):-!.
adjetivo(["verdes"],["green"],f,p):-!.
adjetivo(["viejo"],["old"],m,s):-!.
adjetivo(["viejos"],["old"],m,p):-!.
adjetivo(["vieja"],["old"],f,s):-!.
adjetivo(["viejas"],["old"],f,p):-!.
adjetivo(["vivo"],["alive"],m,s):-!.
adjetivo(["vivos"],["alive"],m,p):-!.
adjetivo(["viva"],["alive"],f,s):-!.
adjetivo(["vivas"],["alive"],f,p):-!.
