
%Pronombres persona cantidad tiempo sexo
pronombre(["yo"],["i"],p,s,mf):-!.
pronombre(["usted"],["you"],s,s,mf):-!.
pronombre(["ella"],["she"],t,s,f):-!.
pronombre(["el"],["he"],t,s,f):-!.
pronombre(["eso"],["it"],t,s,mf):-!.
pronombre(["nosotros"],["we"],p,p,m):-!.
pronombre(["nosotras"],["we"],p,p,f):-!.
pronombre(["ustedes"],["you"],s,p,mf):-!.
pronombre(["ellas"],["they"],t,p,f):-!.
pronombre(["ellos"],["they"],t,p,m):-!.

%Verbos auxiliares en pregunta
preg(["yo"],["do","i"],i,s,pr):-!.
preg(["usted"],["do","you"],i,s,pr):-!.
preg(["el"],["does","he"],m,s,pr):-!.
preg(["ella"],["does","she"],f,s,pr):-!.
preg(["eso"],["does","it"],i,s,pr):-!.
preg(["ustedes"],["do","you"],i,p,pr):-!.
preg(["ellos"],["do","they"],m,p,pr):-!.
preg(["ellas"],["do","they"],f,p,pr):-!.

preg(["usted"],["did","you"],i,s,pa):-!.
preg(["el"],["did","he"],m,s,pa):-!.
preg(["ella"],["did","she"],f,s,pa):-!.
preg(["eso"],["did","it"],i,s,pa):-!.
preg(["ustedes"],["did","you"],i,p,pa):-!.
preg(["ellos"],["did","they"],m,p,pa):-!.
preg(["ellas"],["did","they"],f,p,pa):-!.

preg(["usted"],["were","you"],i,s,pa):-!.
preg(["el"],["was","he"],m,s,pa):-!.
preg(["ella"],["was","she"],f,s,pa):-!.
preg(["eso"],["was","it"],i,s,pa):-!.
preg(["ustedes"],["were","you"],i,p,pa):-!.
preg(["ellos"],["were","they"],m,p,pa):-!.
preg(["ellas"],["were","they"],f,p,pa):-!.

preg(["usted"],["will","you"],i,s,f):-!.
preg(["el"],["will","he"],m,s,f):-!.
preg(["ella"],["will","she"],f,s,f):-!.
preg(["eso"],["will","it"],i,s,f):-!.
preg(["ustedes"],["will","you"],i,p,f):-!.
preg(["ellos"],["will","they"],m,p,f):-!.
preg(["ellas"],["will","they"],f,p,f):-!.


%Auxiliares
aux([""],["do"],p,s,pr):-!.
aux([""],["do"],s,s,pr):-!.
aux([""],["does"],t,s,pr):-!.
aux([""],["do"],p,p,pr):-!.
aux([""],["do"],s,p,pr):-!.
aux([""],["do"],t,p,pr):-!.
aux(["no"],["dont"],p,s,pr):-!.
aux(["no"],["dont"],s,s,pr):-!.
aux(["no"],["doesnt"],t,s,pr):-!.
aux(["no"],["dont"],p,p,pr):-!.
aux(["no"],["dont"],s,p,pr):-!.
aux(["no"],["dont"],t,p,pr):-!.

aux([""],["did"],p,s,pa):-!.
aux([""],["did"],s,s,pa):-!.
aux([""],["did"],t,s,pa):-!.
aux([""],["did"],p,p,pa):-!.
aux([""],["did"],s,p,pa):-!.
aux([""],["did"],t,p,pa):-!.
aux(["no"],["didnt"],p,s,pa):-!.
aux(["no"],["didnt"],s,s,pa):-!.
aux(["no"],["didnt"],t,s,pa):-!.
aux(["no"],["didnt"],p,p,pa):-!.
aux(["no"],["didnt"],s,p,pa):-!.
aux(["no"],["didnt"],t,p,pa):-!.

%Sustantivos
sustantivo(["nariz"],["nose"],f,s).
sustantivo(["carro"],["car"],m,s).
sustantivo(["carros"],["cars"],m,p).
sustantivo(["perro"],["dog"],m,s).
sustantivo(["perros"],["dogs"],m,p).
sustantivo(["manzana"],["apple"],f,s).
sustantivo(["manzanas"],["apples"],f,p).
sustantivo(["hermano"],["brother"],m,s).
sustantivo(["hermanos"],["brothers"],m,p).
sustantivo(["edad"],["age"],f,s).
sustantivo(["edades"],["ages"],f,p).
sustantivo(["aire"],["air"],m,s).
sustantivo(["animal"],["animal"],m,s).
sustantivo(["animales"],["animals"],m,p).
sustantivo(["respuesta"],["answer"],f,s).
sustantivo(["respuestas"],["answers"],f,p).
sustantivo(["arte"],["art"],m,s).
sustantivo(["bebe"],["baby"],m,s).
sustantivo(["bebes"],["babies"],m,p).
sustantivo(["bola"],["ball"],f,s).
sustantivo(["bolas"],["balls"],f,p).
sustantivo(["banco"],["bank"],m,s).
sustantivo(["cama"],["bed"],f,s).
sustantivo(["camas"],["beds"],f,p).
sustantivo(["factura"],["bill"],f,s).
sustantivo(["facturas"],["bills"],f,p).
sustantivo(["pajaro"],["bird"],m,s).
sustantivo(["pajaros"],["birds"],m,p).
sustantivo(["sangre"],["blood"],f,s).
sustantivo(["barco"],["boat"],m,s).
sustantivo(["barcos"],["boats"],m,p).
sustantivo(["cuerpo"],["body"],m,s).
sustantivo(["hueso"],["bone"],m,s).
sustantivo(["huesos"],["bones"],m,p).
sustantivo(["libro"],["book"],m,s).
sustantivo(["libros"],["books"],m,p).
sustantivo(["fondo"],["bottom"],m,s).
sustantivo(["caja"],["box"],f,s).
sustantivo(["cajas"],["boxes"],f,p).
sustantivo(["nino"],["boy"],m,s).
sustantivo(["ninos"],["boys"],m,p).
sustantivo(["nina"],["girl"],f,s).
sustantivo(["niñas"],["girls"],f,p).
sustantivo(["edificio"],["building"],m,s).
sustantivo(["edificios"],["buildings"],m,p).
sustantivo(["negocio"],["business"],m,s).
sustantivo(["llamada"],["call"],f,s).
sustantivo(["llamadas"],["calls"],f,p).
sustantivo(["capital"],["capital"],f,s).
sustantivo(["centro"],["center"],m,s).
sustantivo(["siglo"],["century"],m,s).
sustantivo(["siglos"],["centuries"],m,p).
sustantivo(["oportunidad"],["chance"],f,s).
sustantivo(["oportunidades"],["chances"],f,p).
sustantivo(["cambio"],["change"],m,s).
sustantivo(["cambios"],["changes"],m,p).
sustantivo(["iglesia"],["church"],f,s).
sustantivo(["iglesias"],["churches"],f,p).
sustantivo(["circulo"],["circle"],m,s).
sustantivo(["cuidad"],["city"],f,s).
sustantivo(["cuidades"],["cities"],f,p).
sustantivo(["clase"],["class"],f,s).
sustantivo(["clases"],["classes"],f,p).
sustantivo(["ropa"],["clothes"],f,s).
sustantivo(["nube"],["cloud"],f,s).
sustantivo(["nubes"],["clouds"],f,p).
sustantivo(["costa"],["coast"],f,s).
sustantivo(["color"],["color"],m,s).
sustantivo(["colores"],["colors"],m,p).
sustantivo(["empresa"],["company"],f,s).
sustantivo(["empresas"],["companies"],f,p).
sustantivo(["copia"],["copy"],f,s).
sustantivo(["copias"],["copies"],f,p).
sustantivo(["maiz"],["corn"],m,s).
sustantivo(["algodon"],["cotton"],m,s).
sustantivo(["pais"],["country"],m,s).
sustantivo(["paises"],["countries"],m,p).
sustantivo(["curso"],["course"],m,s).
sustantivo(["vaca"],["cow"],f,s).
sustantivo(["vacas"],["cows"],f,p).
sustantivo(["multitud"],["crowd"],f,s).
sustantivo(["dia"],["day"],m,s).
sustantivo(["dias"],["days"],m,p).
sustantivo(["distancia"],["distance"],f,s).
sustantivo(["medico"],["doctor"],m,s).
sustantivo(["puerta"],["door"],f,s).
sustantivo(["puertas"],["doors"],f,p).
sustantivo(["oreja"],["ear"],f,s).
sustantivo(["orejas"],["ears"],f,p).
sustantivo(["tierra"],["earth"],f,s).
sustantivo(["huevo"],["egg"],m,s).
sustantivo(["huevos"],["eggs"],m,p).
sustantivo(["energia"],["energy"],f,s).
sustantivo(["ejemplo"],["example"],m,s).
sustantivo(["experiencia"],["experience"],f,s).
sustantivo(["experiencias"],["experiences"],f,p).
sustantivo(["ojo"],["eye"],m,s).
sustantivo(["ojos"],["eyes"],m,p).
sustantivo(["juego"],["game"],m,s).
sustantivo(["juegos"],["games"],m,p).
sustantivo(["jardin"],["garden"],m,s).
sustantivo(["vidrio"],["glass"],m,s).
sustantivo(["vidrios"],["glasses"],m,p).
sustantivo(["oro"],["gold"],m,s).
sustantivo(["gobierno"],["government"],m,s).
sustantivo(["cesped"],["grass"],m,s).
sustantivo(["grupo"],["group"],m,s).
sustantivo(["grupos"],["groups"],m,p).
sustantivo(["pelo"],["hair"],m,s).
sustantivo(["mano"],["hand"],f,s).
sustantivo(["manos"],["hands"],f,p).
sustantivo(["sombrero"],["hat"],m,s).
sustantivo(["sombreros"],["hats"],m,p).
sustantivo(["cabeza"],["head"],f,s).
sustantivo(["corazon"],["heart"],m,s).
sustantivo(["historia"],["history"],f,s).
sustantivo(["historias"],["histories"],f,p).
sustantivo(["agujero"],["hole"],m,s).
sustantivo(["agujeros"],["holes"],m,p).
sustantivo(["casa"],["house"],f,s).
sustantivo(["casas"],["houses"],f,p).
sustantivo(["hogar"],["home"],m,s).
sustantivo(["hielo"],["ice"],m,s).
sustantivo(["idea"],["idea"],f,s).
sustantivo(["ideas"],["ideas"],f,p).
sustantivo(["industria"],["industry"],f,s).
sustantivo(["industrias"],["industries"],f,p).
sustantivo(["informacion"],["information"],f,s).
sustantivo(["insecto"],["insect"],m,s).
sustantivo(["insectos"],["insects"],m,p).
sustantivo(["interes"],["interest"],m,s).
sustantivo(["hierro"],["iron"],m,s).
sustantivo(["isla"],["island"],f,s).
sustantivo(["islas"],["islands"],f,p).
sustantivo(["llave"],["key"],f,s).
sustantivo(["llaves"],["keys"],f,p).
sustantivo(["lago"],["lake"],m,s).
sustantivo(["lagos"],["lakes"],m,p).
sustantivo(["idioma"],["language"],m,s).
sustantivo(["idiomas"],["languages"],m,p).
sustantivo(["ley"],["law"],f,s).
sustantivo(["leyes"],["laws"],f,p).
sustantivo(["pierna"],["leg"],f,s).
sustantivo(["piernas"],["legs"],f,p).
sustantivo(["nivel"],["level"],m,s).
sustantivo(["niveles"],["levels"],m,p).
sustantivo(["mentira"],["lie"],f,s).
sustantivo(["mentiras"],["lies"],f,p).
sustantivo(["vida"],["life"],f,s).
sustantivo(["luz"],["light"],f,s).
sustantivo(["linea"],["line"],f,s).
sustantivo(["lista"],["list"],f,s).
sustantivo(["maquina"],["machine"],f,s).
sustantivo(["hombre"],["man"],m,s).
sustantivo(["hombres"],["men"],m,p).
sustantivo(["material"],["material"],m,s).
sustantivo(["materiales"],["materials"],m,p).
sustantivo(["carne"],["meat"],f,s).
sustantivo(["medio"],["middle"],m,s).
sustantivo(["milla"],["mile"],f,s).
sustantivo(["millas"],["miles"],f,p).
sustantivo(["leche"],["milk"],f,s).
sustantivo(["mente"],["mind"],f,s).
sustantivo(["minuto"],["minute"],m,s).
sustantivo(["minutos"],["minutes"],m,p).
sustantivo(["dinero"],["money"],m,s).
sustantivo(["mes"],["month"],m,s).
sustantivo(["luna"],["moon"],f,s).
sustantivo(["boca"],["mouth"],f,s).
sustantivo(["musica"],["music"],f,s).
sustantivo(["nacion"],["nation"],f,s).
sustantivo(["noche"],["night"],f,s).
sustantivo(["nota"],["note"],f,s).
sustantivo(["numero"],["number"],m,s).
sustantivo(["numeros"],["numbers"],m,p).
sustantivo(["objeto"],["object"],m,s).
sustantivo(["objetos"],["objects"],m,p).
sustantivo(["oceano"],["ocean"],m,s).
sustantivo(["oficina"],["office"],f,s).
sustantivo(["pagina"],["page"],f,s).
sustantivo(["papel"],["paper"],m,s).
sustantivo(["parrafo"],["paragraph"],m,s).
sustantivo(["parque"],["park"],m,s).
sustantivo(["parte"],["part"],f,s).
sustantivo(["partes"],["parts"],f,p).
sustantivo(["fiesta"],["party"],f,s).
sustantivo(["pasado"],["past"],m,s).
sustantivo(["persona"],["person"],f,s).
sustantivo(["personas"],["people"],f,p).
sustantivo(["presidente"],["president"],m,s).
sustantivo(["problema"],["problem"],m,s).
sustantivo(["producto"],["product"],m,s).
sustantivo(["propiedad"],["property"],f,s).
sustantivo(["pregunta"],["question"],f,s).
sustantivo(["carrera"],["race"],f,s).
sustantivo(["radio"],["radio"],m,s).
sustantivo(["lluvia"],["rain"],f,s).
sustantivo(["razon"],["reason"],f,s).
sustantivo(["record"],["record"],m,s).
sustantivo(["anillo"],["ring"],m,s).
sustantivo(["rio"],["river"],m,s).
sustantivo(["camino"],["road"],m,s).
sustantivo(["caminos"],["roads"],m,p).
sustantivo(["roca"],["rock"],f,s).
sustantivo(["fila"],["row"],f,s).
sustantivo(["regla"],["rule"],f,s).
sustantivo(["escuela"],["school"],f,s).
sustantivo(["ciencia"],["science"],f,s).
sustantivo(["asiento"],["seat"],m,s).
sustantivo(["segundo"],["second"],m,s).
sustantivo(["segundos"],["seconds"],m,p).
sustantivo(["señal"],["sign"],f,s).
sustantivo(["hermana"],["sister"],f,s).
sustantivo(["tamaño"],["size"],m,s).
sustantivo(["piel"],["skin"],f,s).
sustantivo(["nieve"],["snow"],f,s).
sustantivo(["solucion"],["solution"],f,s).
sustantivo(["hijo"],["son"],m,s).
sustantivo(["hija"],["daughter"],f,s).
sustantivo(["primavera"],["spring"],f,s).
sustantivo(["estrella"],["star"],f,s).
sustantivo(["estrellas"],["stars"],f,s).
sustantivo(["estado"],["state"],m,s).
sustantivo(["calle"],["street"],f,s).
sustantivo(["estudiante"],["student"],m,s).
sustantivo(["azucar"],["sugar"],m,s).
sustantivo(["sol"],["sun"],m,s).
sustantivo(["pueblo"],["village"],m,s).
sustantivo(["guerra"],["war"],f,s).
sustantivo(["tiempo"],["weather"],m,s).
sustantivo(["peso"],["weight"],m,s).
sustantivo(["ventana"],["window"],f,s).
sustantivo(["invierno"],["winter"],m,s).
sustantivo(["mujer"],["woman"],f,s).
sustantivo(["mujeres"],["women"],f,p).
sustantivo(["palabra"],["word"],f,s).
sustantivo(["palabras"],["words"],f,p).
sustantivo(["mundo"],["world"],m,s).
sustantivo(["año"],["year"],m,s).
sustantivo(["años"],["years"],m,p).
sustantivo(["libro"],["book"],m,s).
sustantivo(["libros"],["books"],m,p).

